version: '2.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always 
    environment:
      - DATABASE_HOST=mysql_server
      - DATABASE_PORT=3306
      - DATABASE_USER=user_using_mysql
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=skates_shop
      - PORT=8080
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:  
      - MYSQL_DATABASE=skates_shop
      - MYSQL_USER=user_using_mysql
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
